- id: Вызов меню управления телеграм
  alias: telegram_menu_start
  initial_state: true
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /go
  action:
  - service: telegram_bot.send_message
    data:
      target: '{{ trigger.event.data.chat_id }}'
      message: '{{''\U0001F527''}} Выбери камеру :

        '
      inline_keyboard:
      - "{{'\\U0001F4F8'}} Подъезд:/en_control , {{'\\U0001F4FD\t'}} Улица:/bt_control"
      - '{{''\U0001F4F9''}} Видео с подъезда:/vi_control'
      - '{{''\U0001F6AB''}} Убрать меню:/menu_hide'
- id: Главное меню управления телеграм
  alias: telegram_menu_control
  initial_state: true
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data: {}
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/menu_hide'' }}'
      sequence:
      - service: telegram_bot.delete_message
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/menu_back'' }}'
      sequence:
      - service: telegram_bot.delete_message
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
      - service: telegram_bot.send_message
        data:
          target: '{{ trigger.event.data.chat_id }}'
          message: '{{''\U0001F527''}} Выбери камеру :

            '
          inline_keyboard:
          - "{{'\\U0001F4F8'}} Подъезд:/en_control , {{'\\U0001F4FD\t'}} Улица:/bt_control"
          - '{{''\U0001F4F9''}} Видео с подъезда:/vi_control'
          - '{{''\U0001F6AB''}} Убрать меню:/menu_hide'
- id: Xiaofang shot
  alias: Xiaofang shot
  description: Xiaofang shot
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data: {}
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/en_control'' }}'
      sequence:
      - service: telegram_bot.delete_message
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
      - service: camera.snapshot
        data:
          entity_id: camera.xiaofang
          filename: /config/www/cam_captures/xiaofang.jpg
      - delay:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
      - service: telegram_bot.send_photo
        data_template:
          target: '{{ trigger.event.data.chat_id }}'
        data:
          file: /config/www/cam_captures/xiaofang.jpg
          caption: Фото сделано в - {{ states('sensor.time_date') }}
- id: ip cam shot
  alias: ip cam shot
  description: ip cam shot
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data: {}
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/bt_control'' }}'
      sequence:
      - service: telegram_bot.delete_message
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
      - service: camera.snapshot
        data:
          entity_id: camera.ip
          filename: /config/www/cam_captures/ip.jpg
      - delay:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
      - service: telegram_bot.send_photo
        data_template:
          target: '{{ trigger.event.data.chat_id }}'
        data:
          file: /config/www/cam_captures/ip.jpg
          caption: Фото сделано в - {{ states('sensor.time_date') }}
- id: Xiaofang video
  alias: Xiaofang video
  description: Xiaofang video
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data: {}
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/vi_control'' }}'
      sequence:
      - service: telegram_bot.delete_message
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
      - service: telegram_bot.send_video
        data_template:
          target: '{{ trigger.event.data.chat_id }}'
        data:
          file: /config/www/cam_captures/xi.mp4
          caption: Видео сделано в - {{ states('sensor.time_date') }}
          target: []
          disable_notification: true
          timeout: 1000
